# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FillIslandInTheSea' do
  pod 'AFNetworking', '3.2.1', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
  pod 'Masonry'


  # Pods for FillIslandInTheSea

  target 'FillIslandInTheSeaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FillIslandInTheSeaUITests' do
    # Pods for testing
  end

end
